#!/bin/tcsh

#BSUB -P P93300041            # project code
#BSUB -W 06:00               # wall-clock time (hrs:mins)
#BSUB -n 1                   # number of tasks in job         
#BSUB -R "span[ptile=1]"     # run 1 task per node
#BSUB -J j1                  # job name
#BSUB -o j1.%J.out           # output file name in which %J is replaced by the job ID
#BSUB -e j1.%J.err           # error file name in which %J is replaced by the job ID
#BSUB -q caldera             # queue

#run the executable
#bash param.sh
bash run_ens.sh
